CREATE TABLE GV_CN(
	[MaLop] [varchar](10) NOT NULL,
	[Magv] [varchar](10) NOT NULL,
	[HocKy] [varchar](10) NOT NULL,
 CONSTRAINT [PK_GV_CN] PRIMARY KEY CLUSTERED 
(
	[MaLop] ASC,
	[Magv] ASC,
	[HocKy] ASC
))
GO
ALTER TABLE GV_CN  WITH CHECK ADD  CONSTRAINT [FK_GV_CN_LOP_1] FOREIGN KEY([MaLop])
REFERENCES [dbo].[LOP_1] ([MaLop])
GO
ALTER TABLE GV_CN CHECK CONSTRAINT [FK_GV_CN_LOP_1]
GO
ALTER TABLE GV_CN WITH CHECK ADD  CONSTRAINT [CK_hocky] CHECK (([hocky]>'2'))
GO
ALTER TABLE GV_CN CHECK CONSTRAINT [CK_hocky]
GO




