CREATE TABLE DKMH(
	[MalopHp] [varchar](10) NOT NULL,
	[MaSV] [varchar](10) NOT NULL,
	[DiemTP] [float] NULL,
	[DiemThi] [float] NULL,
	[PhanTramThi] [float] NULL,
 CONSTRAINT [PK_DKMH] PRIMARY KEY CLUSTERED 
(
	[MalopHp] ASC,
	[MaSV] ASC
))
GO
ALTER TABLE DKMH WITH CHECK ADD  CONSTRAINT [FK_DKMH_LopHP] FOREIGN KEY([MalopHp])
REFERENCES [dbo].[LopHP] ([MaLopHP])
GO
ALTER TABLE DKMH CHECK CONSTRAINT [FK_DKMH_LopHP]
GO
ALTER TABLE DKMH  WITH CHECK ADD  CONSTRAINT [FK_DKMH_Sinh_vien] FOREIGN KEY([MaSV])
REFERENCES [dbo].[Sinh_vien] ([MSSV])
GO
ALTER TABLE DKMH CHECK CONSTRAINT [FK_DKMH_Sinh_vien]
GO


